### PR TITLE
training on the tensorflow backend

### PR DESCRIPTION
**Pull request by ylxdzsw**

### CODE REVIEW

**Comment by MikeInnes** [comment]
Great, thanks!

**Comment by MikeInnes** [comment]
Actually, I'll need to revert this as it fails the TensorFlow tests. Can you please fix that?

**Comment by ylxdzsw** [comment]
Yes, didn't notice that, I will take a look. There are some generic training tests on the optimizer branch, we can also add tests of the training process of backends there.

**Comment by ylxdzsw** [comment]
I have fixed some bugs on this branch, maybe reopen it and merge again?

There is still a test that fails, the error info is strange:

```
Error During Test
  Got an exception of type RemoteException outside of a @test
  On worker 2:
  KeyError: key "message" not found
  getindex at /home/ylxdzsw/.julia/v0.6/PyCall/src/PyCall.jl:244
  getindex at /home/ylxdzsw/.julia/v0.6/PyCall/src/PyCall.jl:249
  py_gradients at /home/ylxdzsw/.julia/v0.6/TensorFlow/src/py.jl:44
  #65 at /home/ylxdzsw/.julia/v0.6/TensorFlow/src/TensorFlow.jl:171
  #110 at ./distributed/process_messages.jl:275 [inlined]
  run_work_thunk at ./distributed/process_messages.jl:56
  run_work_thunk at ./distributed/process_messages.jl:65 [inlined]
  #96 at ./event.jl:73
  Stacktrace:
   [1] #remotecall_wait#146(::Array{Any,1}, ::Function, ::Function, ::Base.Distributed.Worker) at ./distributed/remotecall.jl:382
   [2] remotecall_wait(::Function, ::Base.Distributed.Worker) at ./distributed/remotecall.jl:373
   [3] #remotecall_wait#149(::Array{Any,1}, ::Function, ::Function, ::Int64) at ./distributed/remotecall.jl:394
   [4] remotecall_wait(::Function, ::Int64) at ./distributed/remotecall.jl:394
   [5] gradients(::Array{TensorFlow.Tensor{Float32},1}, ::Array{TensorFlow.Tensor{Float32},1}, ::Array{TensorFlow.Tensor{Float32},1}) at /home/ylxdzsw/.julia/v0.6/TensorFlow/src/core.jl:1519
   [6] gradients at /home/ylxdzsw/.julia/v0.6/TensorFlow/src/core.jl:1534 [inlined]
   [7] (::Flux.TF.##10#18)(::TensorFlow.Tensor{Float32}) at /home/ylxdzsw/.julia/v0.6/Flux/src/backend/tensorflow/model.jl:21
   [8] #makesession#4(::TensorFlow.Session, ::Function, ::Flux.Capacitor, ::Tuple{Array{Float32,2}}) at /home/ylxdzsw/.julia/v0.6/Flux/src/backend/tensorflow/model.jl:21
   [9] (::Flux.TF.Model)(::Array{Float32,2}, ::Vararg{Array{Float32,2},N} where N) at /home/ylxdzsw/.julia/v0.6/Flux/src/backend/tensorflow/model.jl:74
   [10] macro expansion at /home/ylxdzsw/.julia/v0.6/Flux/test/backend/tensorflow.jl:28 [inlined]
   [11] macro expansion at ./test.jl:860 [inlined]
   [12] macro expansion at /home/ylxdzsw/.julia/v0.6/Flux/test/backend/tensorflow.jl:26 [inlined]
   [13] macro expansion at ./test.jl:860 [inlined]
   [14] anonymous at ./<missing>:?
   [15] include_from_node1(::String) at ./loading.jl:569
   [16] macro expansion at /home/ylxdzsw/.julia/v0.6/Flux/test/runtests.jl:22 [inlined]
   [17] macro expansion at ./test.jl:860 [inlined]
   [18] anonymous at ./<missing>:?
```

It is from the test of `svd`. I don't know what happens here but other functions are working well. From the error message I think it's not caused by our side, so I disabled this test for now.

**Comment by oxinabox** [comment]
Can you attempt to MWE that error,
and raise an issue on TensorFlow.jl?

Seeing at https://github.com/malmaud/TensorFlow.jl/blob/master/src/py.jl#L44
there is a error being thrown in the python process, but then there is an error thrown in the exception handling code, because the python Exception doesn't have a message field.

**Comment by ylxdzsw** [comment]
Yes, I'm using

```
Python 3.6.2 (default, Jul 20 2017, 03:52:27) 
[GCC 7.1.1 20170630] on linux
```

I guess the error is because TensorFlow is not support the gradients of svd (https://github.com/tensorflow/tensorflow/issues/6503). But I'm not sure before seeing the actual error message from tensorflow.

link for the issue on TensorFlow.jl: https://github.com/malmaud/TensorFlow.jl/issues/291

**Comment by oxinabox** [comment]
Yes, issue is indeed https://github.com/tensorflow/tensorflow/issues/6503

I am fixing the message now.

**Comment by MikeInnes** [comment]
I can't reopen the PR (guess you pushed while it was closed) but I merged it in https://github.com/MikeInnes/Flux.jl/commit/cd9521a762539b19597b04d03dcb6697bed9e41c.

**Pull request merged**
